In [1]:
import numpy as np

In [2]:
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)

In [3]:

print(arr)

[1 2 3 4 5]


In [4]:
type(arr)

numpy.ndarray

In [5]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [6]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [7]:
type(arr)

numpy.ndarray

In [8]:

## check the shape of the array

arr.shape

(3, 5)

In [9]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [10]:
arr[2]

array([9, 7, 6, 8, 9])

In [11]:
arr[1:,:2]

array([[2, 3],
       [9, 7]])

In [12]:
arr[:,3:]

array([[4, 5],
       [5, 6],
       [8, 9]])

In [13]:
arr[2:]=100

In [14]:
arr

array([[  1,   2,   3,   4,   5],
       [  2,   3,   4,   5,   6],
       [100, 100, 100, 100, 100]])

In [15]:
arr[arr<3]


array([1, 2, 2])

In [16]:
## Create arrays and reshape

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [17]:
arr1=np.arange(0,10).reshape(2,5)

In [18]:
arr2=np.arange(0,10).reshape(2,5)

In [19]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [20]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
## random distribution
np.random.rand(3,3)

array([[0.19304151, 0.92473921, 0.66204336],
       [0.02837674, 0.88759054, 0.65213782],
       [0.59886874, 0.54586571, 0.27675423]])

In [23]:
arr_ex=np.random.randn(4,4)

In [24]:
arr_ex

array([[ 0.88018862,  0.44716452,  2.25832287, -0.33148015],
       [-1.10582996, -0.80236602,  0.61327731, -1.22129917],
       [-0.01938907,  1.35913013,  0.21380024, -0.13242463],
       [-1.1206595 , -0.58085946,  0.25818895,  1.53096783]])

In [25]:

np.random.randint(0,100,8).reshape(4,2)

array([[50, 22],
       [84, 53],
       [21, 93],
       [49, 70]])

In [26]:
np.random.random_sample((1,5))

array([[0.40856268, 0.06782575, 0.25432613, 0.25830071, 0.4972029 ]])